### ISSUE TITLE
de.thryrallo.vrc.avatar-performance-tools 1.3.6 is missing in vpm repository

### ISSUE THREAD

**Issue by anatawa12** [Thryrallo/vpm-listing#1]
de.thryrallo.vrc.avatar-performance-tools 1.3.6, which was published before, is missing in vpm repository.

This will break the project managed with source control system.

Please note this is not allowed according to vcc docs.

https://vcc.docs.vrchat.com/guides/create-listing
> Do not remove old versions of your VPM packages after publishing them. Removing old versions will break projects using [source control](https://vcc.docs.vrchat.com/vpm/source-control).

**Comment by Thryrallo** [comment]
Sorry that's something I don't think I can fix. 1.3.6 had to be removed because it caused hash issues in all creator companion projects where it was already installed. I asked a vrc dev defore doing so and was told on this specific case removing the release made sense.

Won't happen again in the future.

**Comment by anatawa12** [comment]
I think such situations should be addressed with yank (vrchat-community/creator-companion#204) but VCC doesn't have...sad...

I think this should be addressed somewhere in tools github or somewhere else.

**Comment by Thryrallo** [comment]
Yeah that would have been optimal. I was not aware it would cause issues with version controlled projects. I specifically went and asked a vrc dev to check if it would cause problems (maybe it wasn't known back then)

**Comment by anatawa12** [comment]
The caution "Do not remove old versions of your VPM packages after publishing them. Removing old versions will break projects using source control." is written by me over one year ago in pull request 302, so I think they know it would broke version controlled projects, but I think they just ignored (or accepted) the breakage.
